import os
import json
import oracledb
import pandas as pd


# ==========================================================
# CONFIGURAÇÕES GERAIS DO SISTEMA
# ==========================================================

# tupla com as opções fixas do menu
MENU_OPCOES = (
    "1 - Cadastrar produção animal",
    "2 - Listar produções",
    "3 - Excluir produção",
    "4 - Estimar produção",
    "5 - Consultar estimativas",
    "6 - Sair"
)

# dicionário com alguns exemplos prontos de animais e produção real
ANIMAIS_PRODUCAO = {
    1: {"tipo_animal": "Vaca", "categoria": "Leiteira", "unidade": "litros"},
    2: {"tipo_animal": "Galinha", "categoria": "Poedeira", "unidade": "ovos"},
    3: {"tipo_animal": "Boi", "categoria": "Corte", "unidade": "kg"},
    4: {"tipo_animal": "Porco", "categoria": "Corte", "unidade": "kg"}
}

# dicionário com médias fixas para estimativa
# essa parte fica restrita ao Python, sem Oracle e sem R
MEDIAS_ESTIMADAS = {
    1: {"tipo_animal": "Vaca", "media": 420, "unidade": "litros/mês"},
    2: {"tipo_animal": "Galinha", "media": 24, "unidade": "ovos/mês"},
    3: {"tipo_animal": "Boi", "media": 18, "unidade": "kg/mês"},
    4: {"tipo_animal": "Porco", "media": 12, "unidade": "kg/mês"}
}

# lista que guarda o histórico das estimativas feitas no Python
HISTORICO_ESTIMATIVAS = []

# nomes dos arquivos gerados automaticamente
ARQUIVO_TXT = "relatorio_producao_animal.txt"
ARQUIVO_JSON = "dados_producao_animal.json"
ARQUIVO_CSV = "dados_producao_animal.csv"


# ==========================================================
# FUNÇÕES DE APOIO
# ==========================================================

# essa função limpa a tela do terminal
def limpar_tela():
    os.system("cls" if os.name == "nt" else "clear")


# essa função pausa o programa até o usuário apertar ENTER
def pausar():
    input("\nPressione ENTER para continuar...")


# essa função exibe o título do sistema
def exibir_titulo():
    print("==============================================")
    print(" FAZENDINHA SOLUTIONS - PRODUÇÃO ANIMAL")
    print(" Controle de animais e rendimento produtivo")
    print("==============================================")


# essa função exibe o menu principal
def exibir_menu():
    exibir_titulo()
    for opcao in MENU_OPCOES:
        print(opcao)
    print("==============================================")


# essa função lê um número inteiro positivo
# isso só vai aparecer quando o usuario digitar um número com vírgula ou uma letra, por exemplo.
# É só uma validação simples
def ler_inteiro_positivo(mensagem):
    while True:
        try:
            numero = int(input(mensagem).strip())
            if numero < 0:
                print("Digite um número inteiro positivo.")
            else:
                return numero
        except ValueError:
            print("Digite apenas números inteiros.")


'''essa função lê um número decimal positivo, no caso é utilizado variáveis que
podem ser "valores quebrados", como o rendimento'''
def ler_float_positivo(mensagem):
    while True:
        try:
            numero = float(input(mensagem).strip().replace(",", "."))
            if numero < 0:
                print("Digite um número positivo.")
            else:
                return numero
        except ValueError:
            print("Digite apenas números válidos.")


# essa função lê um texto e não deixa o campo ficar vazio
def ler_texto_nao_vazio(mensagem):
    while True:
        texto = input(mensagem).strip()
        if texto == "":
            print("Este campo não pode ficar vazio.")
        else:
            return texto


# essa função pede uma confirmação simples ao usuário
def confirmar(mensagem):
    resposta = input(mensagem).strip().lower()
    return resposta in ("s", "sim")


# essa função mostra um registro encontrado na tela
def exibir_registro(registro):
    print(f"ID: {registro[0]}")
    print(f"Tipo Animal: {registro[1]}")
    print(f"Categoria: {registro[2]}")
    print(f"Quantidade: {registro[3]}")
    print(f"Rendimento Total: {registro[4]}")
    print(f"Unidade: {registro[5]}")


# ==========================================================
# CONEXÃO COM O BANCO
# ==========================================================

# essa função tenta conectar o Python ao Oracle
def conectar_banco():
    try:
        conn = oracledb.connect(
            user="rm571248",
            password="190408",
            dsn="oracle.fiap.com.br:1521/ORCL"
        )
        return conn
    except Exception as erro:
        print("Erro ao conectar no banco de dados:")
        print(erro)
        return None


# essa função cria a tabela automaticamente caso ela ainda não exista
def criar_tabela_se_necessario(conn):
    sql = """
    CREATE TABLE producao_animal (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        tipo_animal VARCHAR2(30) NOT NULL,
        categoria VARCHAR2(30) NOT NULL,
        quantidade NUMBER NOT NULL,
        rendimento_total NUMBER(10,2) NOT NULL,
        unidade VARCHAR2(20) NOT NULL
    )
    """

    cursor = conn.cursor()

    try:
        cursor.execute(sql)
        conn.commit()
    except Exception as erro:
        if "ORA-00955" not in str(erro):
            print("Erro ao criar tabela:")
            print(erro)
    finally:
        cursor.close()


# ==========================================================
# CONSULTAS AO BANCO
# ==========================================================

# essa função busca todos os registros da tabela
def buscar_todos_os_registros(conn):
    cursor = conn.cursor()
    cursor.execute("""
        SELECT id, tipo_animal, categoria, quantidade, rendimento_total, unidade
        FROM producao_animal
        ORDER BY id
    """)
    dados = cursor.fetchall()
    cursor.close()
    return dados


# essa função busca apenas um registro pelo ID
def consultar_registro_por_id(conn, registro_id):
    cursor = conn.cursor()
    cursor.execute("""
        SELECT id, tipo_animal, categoria, quantidade, rendimento_total, unidade
        FROM producao_animal
        WHERE id = :1
    """, [registro_id])
    registro = cursor.fetchone()
    cursor.close()
    return registro


# ==========================================================
# ATUALIZAÇÃO AUTOMÁTICA DOS ARQUIVOS
# ==========================================================

# essa função transforma os dados do banco em lista de dicionários para o JSON
def converter_para_dicionarios(dados):
    lista_registros = []

    for linha in dados:
        registro = {
            "id": linha[0],
            "tipo_animal": linha[1],
            "categoria": linha[2],
            "quantidade": linha[3],
            "rendimento_total": float(linha[4]),
            "unidade": linha[5]
        }
        lista_registros.append(registro)

    return lista_registros


# essa função atualiza automaticamente os arquivos TXT, JSON e CSV
def atualizar_arquivos(conn):
    try:
        dados = buscar_todos_os_registros(conn)

        # gera o TXT
        with open(ARQUIVO_TXT, "w", encoding="utf-8") as arquivo:
            arquivo.write("RELATÓRIO DE PRODUÇÃO ANIMAL\n")
            arquivo.write("=" * 50 + "\n\n")

            if len(dados) == 0:
                arquivo.write("Não há registros cadastrados.\n")
            else:
                for linha in dados:
                    arquivo.write(f"ID: {linha[0]}\n")
                    arquivo.write(f"Tipo Animal: {linha[1]}\n")
                    arquivo.write(f"Categoria: {linha[2]}\n")
                    arquivo.write(f"Quantidade: {linha[3]}\n")
                    arquivo.write(f"Rendimento Total: {linha[4]}\n")
                    arquivo.write(f"Unidade: {linha[5]}\n")
                    arquivo.write("-" * 50 + "\n")

        # gera o JSON
        with open(ARQUIVO_JSON, "w", encoding="utf-8") as arquivo:
            json.dump(converter_para_dicionarios(dados), arquivo, ensure_ascii=False, indent=4)

        # gera o CSV
        df = pd.DataFrame(
            dados,
            columns=[
                "id",
                "tipo_animal",
                "categoria",
                "quantidade",
                "rendimento_total",
                "unidade"
            ]
        )
        df.to_csv(ARQUIVO_CSV, index=False, encoding="utf-8-sig")

    except Exception as erro:
        print("\nErro ao atualizar arquivos automáticos:")
        print(erro)


# ==========================================================
# COLETA DE DADOS
# ==========================================================

# essa função exibe os exemplos prontos de animais e produção real
def exibir_animais_producao():
    print("\nAnimais e produção:")
    for chave, dados in ANIMAIS_PRODUCAO.items():
        print(f"{chave} - {dados['tipo_animal']} | {dados['categoria']} | {dados['unidade']}")
  


# essa função coleta os dados para cadastro
def coletar_dados_producao():
    exibir_animais_producao()
    escolha = ler_inteiro_positivo("\nEscolha uma opção: ")

    if escolha in ANIMAIS_PRODUCAO:
        tipo_animal = ANIMAIS_PRODUCAO[escolha]["tipo_animal"]
        categoria = ANIMAIS_PRODUCAO[escolha]["categoria"]
        unidade = ANIMAIS_PRODUCAO[escolha]["unidade"]

    else:
        print("\nOpção inválida.")
        pausar()
        return None

    quantidade = ler_inteiro_positivo("Digite a quantidade de animais: ")
    rendimento_total = ler_float_positivo("Digite o rendimento total do grupo: ")

    return tipo_animal, categoria, quantidade, rendimento_total, unidade


# ==========================================================
# ESTIMATIVAS DE PRODUÇÃO - SOMENTE PYTHON
# ==========================================================

# essa função exibe os animais disponíveis para estimativa
def exibir_animais_estimativa():
    print("\nAnimais disponíveis para estimativa:")
    for chave, dados in MEDIAS_ESTIMADAS.items():
        print(f"{chave} - {dados['tipo_animal']} | média: {dados['media']} {dados['unidade']}")


# essa função faz uma estimativa rápida de produção
# ela não usa Oracle e não envia nada para o R
def estimar_producao():
    limpar_tela()
    exibir_titulo()
    print("ESTIMATIVA DE PRODUÇÃO\n")

    exibir_animais_estimativa()
    escolha = ler_inteiro_positivo("\nEscolha o tipo de animal: ")

    if escolha not in MEDIAS_ESTIMADAS:
        print("\nOpção inválida para estimativa.")
        pausar()
        return

    quantidade = ler_inteiro_positivo("Digite a quantidade de animais que deseja estimar: ")

    tipo_animal = MEDIAS_ESTIMADAS[escolha]["tipo_animal"]
    media = MEDIAS_ESTIMADAS[escolha]["media"]
    unidade = MEDIAS_ESTIMADAS[escolha]["unidade"]

    producao_estimada = quantidade * media

    estimativa = {
        "tipo_animal": tipo_animal,
        "quantidade_planejada": quantidade,
        "media_por_animal": media,
        "producao_estimada": producao_estimada,
        "unidade": unidade
    }

    HISTORICO_ESTIMATIVAS.append(estimativa)

    print("\nESTIMATIVA GERADA COM SUCESSO!")
    print(f"Animal: {tipo_animal}")
    print(f"Quantidade planejada: {quantidade}")
    print(f"Média por animal: {media} {unidade}")
    print(f"Produção estimada: {producao_estimada} {unidade}")

    pausar()


# essa função mostra o histórico das estimativas feitas no Python
def consultar_estimativas():
    limpar_tela()
    exibir_titulo()
    print("CONSULTA DE ESTIMATIVAS\n")

    if len(HISTORICO_ESTIMATIVAS) == 0:
        print("Não há estimativas registradas no momento.")
    else:
        print("HISTÓRICO DE ESTIMATIVAS")
        print("─" * 85)

        print(f"{'Animal':<15} {'Qtd Planejada':<15} {'Média':<10} {'Produção Estimada':<20} {'Unidade':<15}")
        print("─" * 85)

        for est in HISTORICO_ESTIMATIVAS:
            print(f"{est['tipo_animal']:<15} {est['quantidade_planejada']:<15} {est['media_por_animal']:<10} {est['producao_estimada']:<20} {est['unidade']:<15}")

        print("─" * 85)

    pausar()
'''Nessa parte, optei por exibir a tabela manualmente com colunas alinhadas,
para que os valores não baguncem a visualização no terminal.'''

# ==========================================================
# CRUD
# ==========================================================
# A parte do crud diz respeito principalmente ao banco de dados. Observe a diferença dos "comandos" aqui

# essa função cadastra uma nova produção no banco
def cadastrar_producao(conn):
    limpar_tela()
    exibir_titulo()
    print("CADASTRO DE PRODUÇÃO ANIMAL\n")

    try:
        dados = coletar_dados_producao()

        if dados is None:
            return

        cursor = conn.cursor()
        cursor.execute("""
            INSERT INTO producao_animal
            (tipo_animal, categoria, quantidade, rendimento_total, unidade)
            VALUES (:1, :2, :3, :4, :5)
        """, list(dados))
        conn.commit()
        cursor.close()

        atualizar_arquivos(conn)

        print("\nProdução cadastrada com sucesso!")

    except Exception as erro:
        print("\nErro ao cadastrar produção:")
        print(erro)

    pausar()


# essa função lista todas as produções cadastradas
def listar_producoes(conn):
    limpar_tela()
    exibir_titulo()
    print("LISTAGEM DE PRODUÇÕES\n")

    try:
        dados = buscar_todos_os_registros(conn)

        if len(dados) == 0:
            print("Não há produções cadastradas.")
        else:
            print("TABELA DE PRODUÇÕES")
            print("─" * 85)

            print(f"{'ID':<4} {'Tipo Animal':<15} {'Categoria':<12} {'Qtd':<8} {'Rendimento':<15} {'Unidade':<15}")
            print("─" * 85)

            for linha in dados:
                print(f"{linha[0]:<4} {linha[1]:<15} {linha[2]:<12} {linha[3]:<8} {linha[4]:<15} {linha[5]:<15}")

            print("─" * 85)

    except Exception as erro:
        print("Erro ao listar produções:")
        print(erro)

    pausar()


# essa função exclui uma produção do banco
def excluir_producao(conn):
    limpar_tela()
    exibir_titulo()
    print("EXCLUSÃO DE PRODUÇÃO\n")

    try:
        registro_id = ler_inteiro_positivo("Digite o ID da produção que deseja excluir: ")
        registro = consultar_registro_por_id(conn, registro_id)

        if registro is None:
            print("\nProdução não encontrada.")
            pausar()
            return

        print("\nProdução encontrada:")
        exibir_registro(registro)

        if confirmar("\nDeseja realmente excluir esta produção? (s/n): "):
            cursor = conn.cursor()
            cursor.execute("DELETE FROM producao_animal WHERE id = :1", [registro_id])
            conn.commit()
            cursor.close()

            atualizar_arquivos(conn)

            print("\nProdução excluída com sucesso!")
        else:
            print("\nExclusão cancelada.")

    except Exception as erro:
        print("\nErro ao excluir produção:")
        print(erro)

    pausar()

# ==========================================================
# FUNÇÃO PRINCIPAL
# ==========================================================

# essa função controla o fluxo principal do sistema
def executar_sistema():
    conn = conectar_banco()

    if conn is None:
        return

    criar_tabela_se_necessario(conn)
    atualizar_arquivos(conn)

    while True:
        limpar_tela()
        exibir_menu()

        while True:
            escolha = ler_inteiro_positivo("Escolha uma opção: ")
            if 1 <= escolha <= 6:
                break
            else:
                print("Escolha apenas opções de 1 a 6.")

        match escolha:
            case 1:
                cadastrar_producao(conn)

            case 2:
                listar_producoes(conn)

            case 3:
                excluir_producao(conn)

            case 4:
                estimar_producao()

            case 5:
                consultar_estimativas()

            case 6:
                print("\nEncerrando o sistema...")
                conn.close()
                break

            case _:
                print("\nOpção inválida.")
                pausar()


# esse trecho inicia o sistema
if __name__ == "__main__":
    executar_sistema()

#SELECT * FROM producao_animal; no oracle
